global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: node_exporter

  dns_sd_configs:
  - names: ['tasks.node-exporter']
    type: A
    port: 9100

- job_name: cadvisor

  dns_sd_configs:
  - names: ['tasks.cadvisor']
    port: 8080
    type: A

- job_name: traefik

  dns_sd_configs:
  - names: ['tasks.traefik']
    port: 8080
    type: A

- job_name: devents

  dns_sd_configs:
  - names: ['tasks.devents']
    port: 9103
    type: A
